---
repository: sproogen/resume-theme
favicon: images/profile.jpeg
version: 2
name: 김가영
title: Frontend Developer
email: 808010x@gmail.com
website: https://github.com/kiminn
darkmode: false
github_username: kiminn
additional_links:
    - title: velog
      icon: fas fa-blog
      url: https://velog.io/@kiminn/posts
about_profile_image: images/profile.jpeg
about_content: >
    안녕하세요. 백엔드 개발자로 일하고 있는 박세환입니다. 신기술과 최신 트렌드에 관심이 많고 새로운 기술을 배우는 것을
    좋아합니다. 개인뿐만 아니라 팀 전체의 생산성을 높이는 것에 관심이 많습니다.

    주 스킬은 <mark>TypeScript</mark>이며, Java8/11를 사용하고 있습니다.


    서울에서 7년차 웹 프론트엔드 엔지니어로 일하고 있으며 아름다운 인터페이스와 애니메이션을 구현하는 것을 좋아합니다. 개발자의 가치는 비즈니스 가치를 구현하는데서 나온다고 믿습니다. 주도적으로 업무를 진행할 수 있는 환경을 선호합니다.
content:
    - title: Projects
      layout: list
      content:
          - layout: top-left
            title: PostMobism
            link: https://velog.io/@kiminn/회고-PostMobism#역할-분담-및-목표
            link_text: Project Memoirs
            additional_links:
                - title: github.com/mobi-MIMIZ/PostMobism
                  icon: fab fa-github
                  url: https://github.com/mobi-MIMIZ/PostMobism
            description: |

                PostMobism은 백엔드 Api를 활용하여 회원가입, 로그인, 게시글 CRUD 그리고 댓글 작성을 할 수 있는 사이트입니다.

                <br>
                ## What Did I Do?
                - <mark>RTK</mark>로 전역상태관리, <mark>RTK Query</mark>사용하여 무한스크롤링 구현

                - <mark>faker.js</mark>를 통한 퍼블리싱, <mark>husky</mark>, <mark>esLint</mark>, <mark>tsconfig</mark> 초기 설정

                - <mark>draw.io</mark>를 통한 시퀀스다이어그램 작성, <mark>ThunderClient</mark>를 사용한 백엔드 Api 예상 및 분석

                - <mark>figma</mark>로 디자인, <mark>github</mark>, <mark>Linear</mark>, <mark>discord</mark>를 통한 협업

                <br>
                ## Tech Stack
                - `React`, `TypeScript`, `styled-component`

                <br><br>

          - title: chap-chap
            link: https://velog.io/@kiminn/회고-chap-chap
            link_text: Project Memoirs
            additional_links:
                - title: github.com/mobi-chap-chap/chap-chap
                  icon: fab fa-github
                  url: https://github.com/mobi-chap-chap/chap-chap
            description: |

                chap-chap 은 다양한 레시피를 검색할 수 있는 사이트입니다.

                공공 데이터 포털의 OpenApi 식품의약품 안전처 조리식품레시피와 Peanut님의 백엔드 Api를 활용하였습니다.

                <br>
                ## What Did I Do?

                - <mark>React-Query</mark>사용하여 전역상태관리 및 무한스크롤링 구현

                - <mark>zod</mark>와 <mark>react-hook-form</mark>을 사용한 회원가입/로그인 로직 구현

                - <mark>figma</mark>로 디자인, <mark>github</mark>, <mark>Linear</mark>, <mark>discord</mark>를 통한 협업

                - <mark>lottiefiles</mark>를 활용한 로딩중 애니메이션 효과

                <br>
                ## Tech Stack
                - `React`, `TypeScript`, `tailwind css`

                <br><br>

          - title: MMM
            link: https://velog.io/@kiminn/회고-MMM
            link_text: Project Memoirs
            additional_links:
                - title: github.com/Manners-Maketh-Market/MMM
                  icon: fab fa-github
                  url: https://github.com/Manners-Maketh-Market/MMM
            description: |

                MMM은 중고 거래와 나눔 항목을 분리하여 중고나라와 번개장터처럼 물건을 사고팔며 채팅까지 할 수 있는 사이트입니다.

                <br>
                ## What Did I Do?

                - <mark>React-Query</mark>사용하여 전역상태관리 및 무한스크롤링 구현

                - <mark>msw</mark>와 <mark>faker.js</mark>를 통한 백엔드 데이터 패칭 전 퍼블리싱

                - <mark>figma</mark>로 디자인, <mark>github</mark>, <mark>discord</mark>를 통한 협업

                - <mark>socket.io</mark> 사용해보기

                <br>
                ## Tech Stack
                - `React`, `styled-component`

                <br><br>

    - title: Experience
      layout: list
      content:
          - layout: top-middle
            title: Mobi Community
            caption: 2023.12 - 2024.2
            sub_title: 프론트엔드
            quote: |
                모비는 값비싼 사교육, 현실적 시간 투자의 결여에 겁먹은 세상의 모든 비전공자들을 위해 무료로 교육을 제공하고 취업 이후의 인프라 형성을 통해 새로운 시작을 응원하는 비영리 단체입니다. 

                현재는 내부 추천으로만 운영되고 있으며 향후 홈페이지 개설 및 외부 공개를 통해 영역을 점차 확장해 나갈 예정입니다

          - layout: top-middle
            sub_title: After Mobi
            description: |
                - NextJS 공부중 (z.com 클론코딩, 노마드코더, 블로그 글 작성 ...)

                <br><br>

          - sub_title: 타입스크립트에 대한 이해와 모비톤을 활용한 프로젝트 (chap-chap)
            description: |
                - 타입스크립트 활용

                - 무한 스크롤링

                - 백엔드 API 분석

                <br><br>

          - sub_title: 보일러 템플릿, 회원가입&로그인 라이브러리, URL히스토리 관리
            description: |
                - 페이지네이션

                - ReactHookForm & YUP

                - 필터링

                - 의존성 주입 및 관심사 분리

                <br><br>

          - sub_title: 디자인 시스템 적용과 관련 다양한 라이브러리의 사용
            description: |
                - storybook을 사용한 컴포넌트 주도 개발

                - emotion 

                - styled-component

                - tailwind css, ui

                - Chakra UI, MUI

                <br><br>

    - title: Skills
      layout: list
      content:
          - layout: left
            title: Frontend
            quote: |
                프로젝트를 진행하며 사용중인 기술스택들 입니다.
            description: |
                - React : 어느정도 할 수 있는지 작성...
                - javascript

    - title: Education
      layout: list
      content:
          - layout: top-middle
            title: 경기대학교 서울캠퍼스
            caption: 2016.3 - 2020.2 | 졸업
            sub_title: 실용음악학과/작곡
          - layout: top-middle
            title: 코리아 IT 학원
            caption: 2023.4 - 2023.10 | 수료
            sub_title: 프론트엔드/주말
          - layout: top-middle
            title: Mobi Community
            caption: 2023.12 - 2024.2
            sub_title: 프론트엔드
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
    sass_dir: _sass
    style: compressed
plugins:
    - jekyll-seo-tag
