---
repository: sproogen/resume-theme
favicon: images/profile.jpeg
version: 2
name: 김가영
title: Frontend Developer
email: 808010x@gmail.com
website: https://github.com/kiminn
darkmode: false
github_username: kiminn
additional_links:
    - title: velog
      icon: fas fa-blog
      url: https://velog.io/@kiminn/posts
about_profile_image: images/profile.jpeg
about_content: >
    안녕하세요. 백엔드 개발자로 일하고 있는 박세환입니다. 신기술과 최신 트렌드에 관심이 많고 새로운 기술을 배우는 것을
    좋아합니다. 개인뿐만 아니라 팀 전체의 생산성을 높이는 것에 관심이 많습니다.

    주 스킬은 <mark>TypeScript<mark>이며, Java8/11를 사용하고 있습니다.


    서울에서 7년차 웹 프론트엔드 엔지니어로 일하고 있으며 아름다운 인터페이스와 애니메이션을 구현하는 것을 좋아합니다. 개발자의 가치는 비즈니스 가치를 구현하는데서 나온다고 믿습니다. 주도적으로 업무를 진행할 수 있는 환경을 선호합니다.
content:
    - title: Projects
      layout: list
      content:
          - layout: left
            title: PostMobism
            link: https://velog.io/@kiminn/회고-PostMobism#역할-분담-및-목표
            link_text: Project Memoirs
            additional_links:
                - title: github.com/mobi-MIMIZ/PostMobism
                  icon: fab fa-github
                  url: https://github.com/mobi-MIMIZ/PostMobism
            quote: >
                PostMobism은 백엔드 Api를 활용하여 회원가입, 로그인, 게시글 CRUD 그리고 댓글 작성을 할 수 있는 사이트입니다.
            description: |

                ## Details
                - <mark>RTK<mark>로 전역상태관리, <mark>RTK Query<mark>사용하여 무한스크롤링 구현

                - <mark>msw<mark>를 통한 목데이터 구상, <mark>husky<mark>, <mark>esLint<mark>, <mark>tsconfig<mark> 초기 설정

                - <mark>draw.io<mark>를 통한 시퀀스다이어그램 작성, <mark>ThunderClient<mark>를 사용한 백엔드 Api 분석

                - <mark>figma<mark>로 디자인, <mark>github<mark>와 <mark>Linear<mark>, <mark>discord<mark>를 통한 협업

                <br>
                ## Tech Stack
                - `React`, `TypeScript`, `styled-component`
          - title: chap-chap
            link: https://velog.io/@kiminn/회고-chap-chap
            link_text: Project Memoirs
            additional_links:
                - title: github.com/mobi-chap-chap/chap-chap
                  icon: fab fa-github
                  url: https://github.com/mobi-chap-chap/chap-chap
            quote: >
                PostMobism은 백엔드 Api를 활용하여 회원가입, 로그인, 게시글 CRUD 그리고 댓글 작성을 할 수 있는 사이트입니다.
            description: |

                ## Details

                - <mark>RTK<mark>로 전역상태관리, <mark>RTK Query<mark>사용하여 무한스크롤링 구현

                - <mark>draw.io<mark>를 통한 시퀀스다이어그램 작성, <mark>ThunderClient<mark>를 사용한 백엔드 Api 분석

                - <mark>figma<mark>로 디자인, <mark>github<mark>와 <mark>Linear<mark>를 사용한 협업

                <br>
                ## Tech Stack
                - `React`, `TypeScript`, `styled-component`
          - title: MMM
            link: https://velog.io/@kiminn/회고-MMM
            link_text: Project Memoirs
            additional_links:
                - title: github.com/Manners-Maketh-Market/MMM
                  icon: fab fa-github
                  url: https://github.com/Manners-Maketh-Market/MMM
            quote: |
                MMM은 중고 거래와 나눔 항목을 분리하여 중고나라와 번개장터처럼 물건을 사고팔며 채팅까지 할 수 있는 사이트입니다.
            description: |

                ## Details

                - <mark>RTK<mark>로 전역상태관리, <mark>RTK Query<mark>사용하여 무한스크롤링 구현

                - <mark>draw.io<mark>를 통한 시퀀스다이어그램 작성, <mark>ThunderClient<mark>를 사용한 백엔드 Api 분석

                - <mark>figma<mark>로 디자인, <mark>github<mark>와 <mark>discord<mark>를 통한 협업

                <br>
                ## Tech Stack
                - `React`, `TypeScript`, `styled-component`
    - title: Experience
      layout: list
      content:
          - layout: left
            title: Frontend
            link: boringcompany.com
            sub_title: Senior Network System Administrator
            caption: November 2017 - Present
            quote: >
                Solving 21st century problems by diging holes and making game changing
                products like the *not a flamethrower*
            description: >
                Every company needs its networks properly administered and The
                Boring Compay is no exception. Digging holes is hard and I play my
                part making sure the whole company stays connected. I lead a team of 5
                people and enjoy driving the company to try new technologies.
    - title: Skills
      layout: list
      content:
          - layout: left
            title: Frontend
            quote: |
                프로젝트를 진행하며 사용중인 기술스택들 입니다.
            description: |
                - React
                - javascript
                -
    - title: Education
      layout: list
      content:
          - layout: top-middle
            title: 경기대학교 서울캠퍼스
            caption: 2016.3 - 2020.2 | 졸업
            sub_title: 실용음악학과/작곡
          - layout: top-middle
            title: 코리아 IT 학원
            caption: 2023.4 - 2023.10 | 수료
            sub_title: 프론트엔드/주말
          - layout: top-middle
            title: Mobi Community
            caption: 2023.12 - 2024.2
            sub_title: 프론트엔드
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
    sass_dir: _sass
    style: compressed
plugins:
    - jekyll-seo-tag
